// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class CourseInst
{
    public int InstId { get; set; }

    public int CourseId { get; set; }

    public string Evaluate { get; set; } = null!;

    public virtual Course Course { get; set; } = null!;

    public virtual Instructor Inst { get; set; } = null!;
}