// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class Course
{
    public int Id { get; set; }

    public string Duration { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string Description { get; set; } = null!;

    public int TopId { get; set; }

    public virtual ICollection<CourseInst> CourseInsts { get; set; } = new List<CourseInst>();

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();

    public virtual Topic Top { get; set; } = null!;
}