// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class DepartmentAndInstructor
{
    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; } = null!;

    public string? InstructorName { get; set; }
}