// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class Instructor
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public decimal Bonus { get; set; }

    public decimal Salary { get; set; }

    public string Address { get; set; } = null!;

    public int HourRate { get; set; }

    public int DeptId { get; set; }

    public virtual ICollection<CourseInst> CourseInsts { get; set; } = new List<CourseInst>();

    public virtual Department Dept { get; set; } = null!;
}