// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFirst.Models;

public partial class ITIDbContext : DbContext
{
    public ITIDbContext()
    {
    }

    public ITIDbContext(DbContextOptions<ITIDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<CourseInst> CourseInsts { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<DepartmentAndInstructor> DepartmentAndInstructors { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<StudCourse> StudCourses { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=Alkahlawy;Initial Catalog=ITIDb;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.ToTable("Course");

            entity.HasIndex(e => e.TopId, "IX_Course_Top_ID");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Duration).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.TopId).HasColumnName("Top_ID");

            entity.HasOne(d => d.Top).WithMany(p => p.Courses).HasForeignKey(d => d.TopId);
        });

        modelBuilder.Entity<CourseInst>(entity =>
        {
            entity.HasKey(e => new { e.InstId, e.CourseId });

            entity.HasIndex(e => e.CourseId, "IX_CourseInsts_CourseId");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseInsts).HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Inst).WithMany(p => p.CourseInsts).HasForeignKey(d => d.InstId);
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.ToTable("Department");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.InsId).HasColumnName("Ins_ID");
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<DepartmentAndInstructor>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("DepartmentAndInstructors");

            entity.Property(e => e.DepartmentId).HasColumnName("Department ID");
            entity.Property(e => e.DepartmentName)
                .HasMaxLength(100)
                .HasColumnName("Department Name");
            entity.Property(e => e.InstructorName)
                .HasMaxLength(100)
                .HasColumnName("Instructor Name");
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.ToTable("Instructor");

            entity.HasIndex(e => e.DeptId, "IX_Instructor_Dept_ID");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Address).HasMaxLength(200);
            entity.Property(e => e.Bonus).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DeptId).HasColumnName("Dept_ID");
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Salary).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Dept).WithMany(p => p.Instructors).HasForeignKey(d => d.DeptId);
        });

        modelBuilder.Entity<StudCourse>(entity =>
        {
            entity.HasKey(e => new { e.StudId, e.CourseId });

            entity.ToTable("Stud_Course");

            entity.HasIndex(e => e.CourseId, "IX_Stud_Course_Course_ID");

            entity.Property(e => e.StudId).HasColumnName("stud_ID");
            entity.Property(e => e.CourseId).HasColumnName("Course_ID");
            entity.Property(e => e.Grade).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Course).WithMany(p => p.StudCourses).HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Stud).WithMany(p => p.StudCourses).HasForeignKey(d => d.StudId);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.ToTable("Student");

            entity.HasIndex(e => e.DepId, "IX_Student_Dep_Id");

            entity.Property(e => e.DepId).HasColumnName("Dep_Id");
            entity.Property(e => e.Fname).HasColumnName("FName");
            entity.Property(e => e.Lname).HasColumnName("LName");

            entity.HasOne(d => d.Dep).WithMany(p => p.Students).HasForeignKey(d => d.DepId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}