// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class StudCourse
{
    public int StudId { get; set; }

    public int CourseId { get; set; }

    public decimal Grade { get; set; }

    public virtual Course Course { get; set; } = null!;

    public virtual Student Stud { get; set; } = null!;
}