// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Fname { get; set; } = null!;

    public string Lname { get; set; } = null!;

    public string Address { get; set; } = null!;

    public int Age { get; set; }

    public int DepId { get; set; }

    public virtual Department Dep { get; set; } = null!;

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();
}