// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task15_ef1.Data;

#nullable disable

namespace task15_ef1.Migrations
{
    [DbContext(typeof(ITIDbContext))]
    [Migration("20250909160732_AddRelations")]
    partial class AddRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task15_ef1.Model.ConventionBased.CourseInst", b =>
                {
                    b.Property<int>("InstId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Evaluate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseInsts");
                });

            modelBuilder.Entity("task15_ef1.Model.ConventionBased.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepId")
                        .HasColumnType("int")
                        .HasColumnName("Dep_Id");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("task15_ef1.Model.ConventionBased.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("task15_ef1.Model.DataAnnotations.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("TopId")
                        .HasColumnType("int")
                        .HasColumnName("Top_ID");

                    b.HasKey("Id");

                    b.HasIndex("TopId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("task15_ef1.Model.DataAnnotations.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HiringDate");

                    b.Property<int>("InsId")
                        .HasColumnType("int")
                        .HasColumnName("Ins_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("task15_ef1.Model.FluentAPI.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Bonus");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_ID");

                    b.Property<int>("HourRate")
                        .HasColumnType("int")
                        .HasColumnName("HourRate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Salary");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("task15_ef1.Model.FluentAPI.StudCourse", b =>
                {
                    b.Property<int>("StudId")
                        .HasColumnType("int")
                        .HasColumnName("stud_ID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_ID");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Grade");

                    b.HasKey("StudId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Stud_Course", (string)null);
                });

            modelBuilder.Entity("task15_ef1.Model.ConventionBased.CourseInst", b =>
                {
                    b.HasOne("task15_ef1.Model.DataAnnotations.Course", "Course")
                        .WithMany("CourseInsts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task15_ef1.Model.FluentAPI.Instructor", "Instructor")
                        .WithMany("CourseInsts")
                        .HasForeignKey("InstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("task15_ef1.Model.ConventionBased.Student", b =>
                {
                    b.HasOne("task15_ef1.Model.DataAnnotations.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("task15_ef1.Model.DataAnnotations.Course", b =>
                {
                    b.HasOne("task15_ef1.Model.ConventionBased.Topic", "Topic")
                        .WithMany("Courses")
                        .HasForeignKey("TopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("task15_ef1.Model.FluentAPI.Instructor", b =>
                {
                    b.HasOne("task15_ef1.Model.DataAnnotations.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("task15_ef1.Model.FluentAPI.StudCourse", b =>
                {
                    b.HasOne("task15_ef1.Model.DataAnnotations.Course", "Course")
                        .WithMany("StudCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task15_ef1.Model.ConventionBased.Student", "Student")
                        .WithMany("StudCourses")
                        .HasForeignKey("StudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("task15_ef1.Model.ConventionBased.Student", b =>
                {
                    b.Navigation("StudCourses");
                });

            modelBuilder.Entity("task15_ef1.Model.ConventionBased.Topic", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("task15_ef1.Model.DataAnnotations.Course", b =>
                {
                    b.Navigation("CourseInsts");

                    b.Navigation("StudCourses");
                });

            modelBuilder.Entity("task15_ef1.Model.DataAnnotations.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("task15_ef1.Model.FluentAPI.Instructor", b =>
                {
                    b.Navigation("CourseInsts");
                });
#pragma warning restore 612, 618
        }
    }
}
